//
//  node.HPP
//  CIS.279
//
//  Created by CIS on 5/4/17.
//  Copyright © 2017 Anthony Nash. All rights reserved.
//


#ifndef node_hpp
#define node_hpp

using namespace std;
namespace ANTHONY_NASH_ASSIGNMENT_4 {

    struct node {
        
        string word;
        int count;
        node* right;
        node* left;
        
    };//class node ...}
    
};//namespace ANTHONY_NASH_ASSIGNMENT_4 ...}

#endif /* node_hpp */
